### ISSUE TITLE
E: Version '3.2.2-2ubuntu2~ubuntu14.04.1~ppa1' for 'cmake' was not found

### ISSUE THREAD

**Issue by anubhavsinha** [ClusterHQ/mesos-module-flocker#15]
When I try to build on a Linux machine (AWS EC2 Ubuntu 14.04LTS) I get these errors when I run
`docker build -t containersol/mesos-modules-dev:14.04 .`

**Comment by sandlbn** [comment]
@anubhavsinha change cmake version to the 3.2.2-2~ubuntu14.04.1~ppa1

**Comment by rorysavage77** [comment]
Just remove that version from the Dockerfile, then it works.

**Comment by tazaki** [comment]
Both solutions worked for me.

**Comment by philwinder** [comment]
Fixed in #16
